version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current  # VM avec Docker préinstallé
    steps:
      - checkout  # Récupération du code source

      - run:
          name: Build Docker Image
          command: docker build -t mon-app:latest .

      - run:
          name: Run Container
          command: docker run -d -p 8080:8080 --name test-container mon-app:latest

      - run:
          name: Test if app is responding
          command: |
            sleep 5  # Attendre que l'application démarre
            curl --fail http://localhost:8080 || exit 1


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
