version: 2.1

jobs:
  build:
    machine:  # Utilisation d'une machine virtuelle au lieu d'un conteneur Docker
      image: ubuntu-2204:current  # Image Ubuntu avec Docker préinstallé
    steps:
      - checkout  # Récupère le code du repo
      - run:
          name: Check Docker Version
          command: docker --version
      - run:
          name: Build Docker image
          command: docker build -t mon-app:latest .
      - run:
          name: Run Container
          command: docker run -d -p 8080:8080 --name test-container mon-app:latest
      - run:
          name: Test if app is responding
          command: |
            sleep 5  # Attendre que le container démarre
            curl --fail http://127.0.0.1:8080 || exit 1
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Tag and Push Image
          command: |
            docker tag mon-app:latest mon-dockerhub-user/mon-app:latest
            docker push mon-dockerhub-user/mon-app:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build