version: 2.1

jobs:
  build:
    machine:  # Utilisation d'une machine virtuelle au lieu d'un conteneur Docker
      image: ubuntu-2204:current  # Image Ubuntu avec Docker préinstallé
    steps:
      - checkout  # Récupère le code du repo
      - run:
          name: Check Docker Version
          command: docker --version
      - run:
          name: Build Docker image
          command: docker build -t mon-app:latest .
      - run:
          name: Run Container
          command: docker run -d -p 8080:8080 --name test-container mon-app:latest
      - run:
          name: Debug - Liste des conteneurs
          command: docker ps -a
      - run:
          name: Test if app is responding
          command: |
            sleep 5  # Attendre que le container démarre
            curl --fail http://127.0.0.1:8080 || exit 1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build