version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Image de base pour l'exécution du job
    steps:
      - checkout  # Récupère le code du repo
      - setup_remote_docker  # Permet d'utiliser Docker dans le job
      - run:
          name: Build Docker image
          command: docker build -t mon-image:latest .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
