version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t mon-app:latest .
      - run:
          name: Test if app is responding
          command: |
            sleep 5  # Attendre que l'application démarre
            docker exec test-container curl --fail http://localhost:8080 || exit 1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
