version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout

      - docker/build:
          image: "$DOCKERHUB_USERNAME/mon-app"
          tag: "latest"

      - run:
          name: Run Container
          command: docker run -d -p 8080:8080 --name test-container "$DOCKERHUB_USERNAME/mon-app:latest"

      - run:
          name: Test if app is responding
          command: |
            sleep 5
            curl --fail http://127.0.0.1:8080 || exit 1

      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - docker/push:
          image: "$DOCKERHUB_USERNAME/mon-app"
          tag: "latest"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
