version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t mon-app:latest .
      - run:
          name: Run Container
          command: docker run -d -p 8080:8080 --name test-container mon-app:latest
      - run:
          name: Test if app is responding
          command: |
            sleep 5  # Attendre que le container démarre
            curl --fail http://127.0.0.1:8080 || exit 1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
