version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t mon-app:latest .
      - run:
          name: Run Container
          command: |
            docker network create test-net
            docker run -d --network test-net --name test-container mon-app:latest
      - run:
          name: Test if app is responding
          command: |
            sleep 5  # Laisse le temps au conteneur de démarrer
            curl --fail http://test-container:8080 || exit 1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
